Add tests to create a new project
Srutip04/neeto-planner-playwright-tests-by-sruti-pingua pull request #11
Opened 2024-04-22 17:51 UTC by Srutip04

Closes #10

2024-04-23 13:27 UTC, shreyakurian02 requested changes
@Srutip04 
It is important to destroy the resources that were created in a test right after they have been executed. Make the fix for the same along with the following suggestions.

2024-04-23 13:27 UTC, shreyakurian02 commented on e2e/poms/projects.ts
> +        expect(this.page).toHaveURL(new RegExp(projectIdentifier.toUpperCase()));
```suggestion
       await  expect(this.page).toHaveURL(new RegExp(projectIdentifier.toUpperCase()));
```

2024-04-23 13:27 UTC, shreyakurian02 commented on e2e/tests/projects.spec.ts
> +        });
Avoid redundant async awaits. 
https://courses.bigbinaryacademy.com/learn-qa-automation-using-playwright/best-practices/#bigbinary-best-practices:~:text=5.-,Avoid,-redundant%20awaits%20when

2024-04-23 17:11 UTC, Srutip04 commented
I've addressed the requested changes in this PR.Please review the changes.

2024-04-24 05:50 UTC, shreyakurian02 approved these changes
@Srutip04 Make the changes and merge the PR.

2024-04-24 05:50 UTC, shreyakurian02 commented on e2e/poms/projects.ts
> +}
```suggestion
    addNewProjectAndVerify = async ({ projectName, projectDescription,projectIdentifier }: Project) => {
        await this.page.getByRole('button', { name: BUTTON_LABELS.addNewProject }).click();
        await this.page.getByPlaceholder(PLACEHOLDERS.projectName).fill(projectName);
        await this.page.getByPlaceholder(PLACEHOLDERS.projectIdentifier).fill(projectIdentifier);
        await this.page.getByPlaceholder(PLACEHOLDERS.projectDescription).fill(projectDescription);
        await this.page.getByRole('button', { name: BUTTON_LABELS.saveChanges }).click();
        await expect(this.page.getByText(new RegExp(projectName, "i"))).toBeVisible();
        await expect(this.page).toHaveURL(new RegExp(projectIdentifier.toUpperCase()));
    }
    
    deleteProject = async ({projectName}) => {
        await expect(this.page.getByText(new RegExp(projectName, "i"))).toBeVisible();
        await this.page.locator('button:nth-child(4)').click();
        await this.page.getByRole('button', { name: BUTTON_LABELS.deleteButton }).click();
        await expect(this.page.getByRole('heading', { name: HEADINGS.deleteProject })).toBeVisible();
        await this.page.getByRole('button', { name: BUTTON_LABELS.deleteButton }).click();
        await expect(this.page.getByRole('button', { name: BUTTON_LABELS.addNewProject })).toBeVisible();
    }
}
```

2024-04-24 05:50 UTC, shreyakurian02 commented on e2e/poms/projects.ts
> +}
Take care of unnecessary spacings.

2024-04-24 05:50 UTC, shreyakurian02 commented on e2e/poms/projects.ts
> +        await this.page.locator('button:nth-child(4)').click();
https://courses.bigbinaryacademy.com/learn-qa-automation-using-playwright/best-practices/#bigbinary-best-practices:~:text=remain%20idle%20indefinitely.-,13,-.%20Avoid%20using%20nth

2024-04-24 05:50 UTC, shreyakurian02 commented on e2e/poms/projects.ts
> +        await this.page.getByRole('button', { name: BUTTON_LABELS.deleteButton }).click();
There is no need to assert for an element to be visible before clicking until absolute necessary.

2024-04-24 05:50 UTC, shreyakurian02 commented on e2e/poms/projects.ts
> +        await expect(this.page.getByRole('button', { name: BUTTON_LABELS.addNewProject })).toBeVisible();
This is not the right way of checking if the project was deleted. What if in parallelism few other projects were created in other tests as well. This test would be highly flaky.

2024-04-24 05:50 UTC, shreyakurian02 requested changes
@Srutip04

2024-04-24 05:50 UTC, shreyakurian02 requested changes
@Srutip04

2024-04-24 05:50 UTC, shreyakurian02 requested changes
@Srutip04

2024-04-24 18:33 UTC, merged